### ISSUE TITLE
Design an approach to keeping up with the latest version of Prefect over time

### ISSUE THREAD

**Issue by chrisguidry** [PrefectHQ/prefect-operator#35]
We have a [hard-coded default Prefect version](https://github.com/PrefectHQ/prefect-operator/blob/main/api/v1/versioning.go#L23) in the `prefect-operator`, but we won't want to make a release every time Prefect has a release (weekly or more frequently).  Instead, let's design an approach that lets the default value come from external configuration, then also have a periodic process to update it.

**Comment by chrisguidry** [comment]
One approach we could take:

* Keep a hard-coded default in the code as a fallback
* Create a `ConfigMap` in the operator's namespace that is storing the latest observed version of Prefect (by periodically checking the Prefect releases via the Github API)
* The operator reads-or-creates this `ConfigMap` at startup to either read the current value or bootstrap it with the hard-coded default
* There's a `CronJob` that periodically (it can be daily or heck, even weekly) to update that value

One thing that's interesting here is what to do with `PrefectServer` or `PrefectWorkPool`s that don't have an explicit version.  Do we update their spec with a default version at the time they are first created?  Do we update their status with that version?  If we do nothing, then every time the `ConfigMap` is updated with a new latest version, any unspecified server or work pool would be updated to that version automatically, which may not be what we want happening at a random time.

**Comment by chrisguidry** [comment]
Should we instead just always require the Prefect version on both objects?  In that case we don't need to worry about this at all.

**Comment by parkedwards** [comment]
re: `CronJob` approach, I haven't seen examples in the wild that handle their app versions like this, though I'm sure it's possible.  It feels a little magical and less explicit from the source code (even though we'd have the default fallthrough), and almost as though we're putting a mini GitRepo controller inside the operator.  Also I can't help but think that we might be susceptible to introducing some pernicious breaking changes, but there are probably some guard rails im not thinking of

> but we won't want to make a release every time Prefect has a release (weekly or more frequently)

is this a problem?  for ex., i believe the [opentelemetry operator](https://github.com/open-telemetry/opentelemetry-operator/releases) cuts a weekly release to keep the app version in sync. maybe we could add automation that kicks off a PR in this repo whenever the `prefect` release is created (similar to how we do our helm charts)

**Comment by mitchnielsen** [comment]
> we could add automation that kicks off a PR in this repo whenever the prefect release is created (similar to how we do our helm charts), so that we can vet it + manually create the operator release

This sounds like a good place to start to me. We can:
- Specify a default version of Prefect that the Operator will deploy.
- That default Prefect version can be overridden in the spec
   - We can document expectations around viable values here (i.e. any patch version is fair game, but a minor version change might break something)
- We can let Dependabot/etc open a PR either when a new version of Prefect arrives, and if it becomes too much to manage we could try weekly or something instead.
- If the tests in that PR pass, we can either manually merge it or let it merge automatically.
- If the new version did break something, we have a chance to fix it in the PR before it's merged.

Since I suspect we'll want to be intentional about upgrading instances to new versions, this feels like a safe and stable way to do it. Always up to try new approaches like your ConfigMap idea though and see how it goes.

**Comment by chrisguidry** [comment]
I like this!  We can move that version constant to its own file to make it extremely easy to automate.  Let's roll with that

**Comment by chrisguidry** [comment]
https://github.com/PrefectHQ/prefect-operator/issues/59
